# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box / OS
VAGRANT_BOX = 'hashicorp/bionic64'
VM_NAME = 'VmGateway'

Vagrant.configure(2) do |config|
  config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX
  # Actual machine name
  config.vm.hostname = VM_NAME
  # Set VM name in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 512
  end

  config.vm.provision "shell", inline: <<-SHELL
    # bash script
    apt-get update

    echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
    echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections

    apt-get install -y tcpdump iptables-persistent

    sed -i "s@#net.ipv4.ip_forward=1@net.ipv4.ip_forward=1@g" /etc/sysctl.conf
    sysctl -p
   
    cp /vagrant/rules.v4 /etc/iptables/rules.v4
    iptables-restore < /etc/iptables/rules.v4

  SHELL
end
